title: linjan2 takes notes
author: Linda Jansson
email: null
description: 
url: linjan2.github.io
baseurl: ''
source_repo: https://github.com/linjan2/linjan2.github.io
repository: linjan2/linjan2.github.io

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-minifier

# theme: minima
remote_theme: jekyll/minima

minima:
  skin: auto
  nav_pages:
    - pages/categories.md
    - pages/about.md
  social_links:
    - title: GitHub
      icon: github
      url: https://github.com/linjan2

defaults:
  - scope:
      path: '' # all
    values:
      author: Linda Jansson
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      permalink: /:title/
  - scope:
      path: pages
    values:
      layout: page

disqus:
  shortname: linda-jansson-com

jekyll-minifier:
  uglifier_args:
    harmony: true
  # js_compressor: terser
  # terser_args:
  #   compress:
  #     arrows: true
  #     ecma: 6
  #   mangle: true
  #   output:
  #     comments: false
